### ISSUE TITLE
React package?

### ISSUE THREAD

**Issue by shivindera** [csauvage/streamline-core#1]
Are the npm packages out? I cant find them anywhere, even in the account.

**Comment by positimo** [comment]
Yeah, what's the status with the NPM package!?

**Comment by robhawkes** [comment]
Also curious about this. The blog post suggests it was coming late 2019 but can't find anything. Is there an update on the React component?

**Comment by akougblenou** [comment]
Same curiosity here is the package still in the works ?

**Comment by djaax** [comment]
On the official website it now says "Include icons with our NPM packages for React, Angular, Vue.js.". This seems to be quite recent but still, I'm unable to add it to my repo. I'm getting the following error on `yarn add @streamline/core`:

`error An unexpected error occurred: "https://registry.yarnpkg.com/@streamline%2fcore: Not found".`

**Comment by csauvage** [comment]
Sorry I'm just realizing i've opened a repo here also monthes ago. 
All you need to know is here : https://www.notion.so/Streamline-Developer-Documentation-7ee5728d4a674b1f886c553a6f81daac

Cheers.
